// react-punk-brew/src/BeerCard.js
import React from 'react'
import { Link } from 'react-router-dom'
import styled from 'styled-components'

const BeerCardWrapper = styled.div`
  background-color: #fff;
  box-shadow: 0px 2px 5px 1px rgba(0,0,0, 0.2);
  max-width: 400px;
  width: 100%;
  margin: 1rem 0;
  padding: 1rem;
  img {
    height: 300px;
    max-width: 100%;
    display: block;
    margin: 0 auto 1em;
  }
`

class BeerCard extends React.Component {
  render() {
    const { beer } = this.props
    return (
      <BeerCardWrapper>
        <img src={beer.image_url} alt={beer.name} />
        <h3>
          {beer.name}
          <br />
          <small>{beer.tagline}</small>
        </h3>

        <p>{beer.description}</p>

        <h4>Food pairing</h4>
        <ul>
          {beer.food_pairing.map((food, i) => <li key={i}>{food}</li> )}
        </ul>

        <Link to={`/beer/${beer.id}`}>More</Link>
      </BeerCardWrapper>
    )
  }
}

export default BeerCard

// vue-punk-brew/src/components/BeerCard.vue



<template>
  <div class="beer-card">
    <img :src="img" :alt="name">
    <h3>
      {{beer.name}}
      <br />
      <small>{{beer.tagline}}</small>
    </h3>

    <p>{{beer.description}}</p>

    <h4>Food pairing</h4>
    <ul>
      <li v-for="food in beer.food_pairing">{{food}}</li>
    </ul>

    <a :href="url">More</a>
  </div>
</template>

<script>
  export default {
    props: ['beer'],
    name: 'beer-card',
    data() {
      return {
        url: `/#/beer/${this.beer.id}`,
        img: this.beer.image_url,
        name: this.beer.name,
      };
    },
  };
</script>

<style scoped>
  .beer-card {
    background-color: #fff;
    box-shadow: 0px 2px 5px 1px rgba(0,0,0, 0.2);
    max-width: 400px;
    width: 100%;
    margin: 1rem 0;
    padding: 1rem;
  }
  img {
    height: 300px;
    max-width: 100%;
    display: block;
    margin: 0 auto 1em;
  }
</style>
