// react-punk-brew/src/PunkHeader.js
import React from 'react'
import styled from 'styled-components'

const Nav = styled.nav`
  background-color: rgba(141, 42, 170, 1);
  display: flex;
  padding: 0px 1em;
`
const H2Header = styled.h2`
  color: #fff;
  font-size: 1.7em;
`
class PunkHeader extends React.Component {
  render() {
    return (
      <Nav>
        <H2Header>Brew Dog Library</H2Header>
      </Nav>
    )
  }
}

export default PunkHeader

// vue-punk-brew/src/components/PunkHeader.vue
<template lang="html">
  <nav>
    <h2>
      Brew Dog Library
    </h2>
  </nav>
</template>

<script>
export default {
};
</script>

<style lang="css" scoped>
  nav {
    background-color: rgba(141, 42, 170, 1);
    display: flex;
    padding: 0px 1em;
  }
  h2 {
    color: #fff;
    font-size: 1.7em;
  }
</style>
